//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VR.Web.UI.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_GetTruck {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_GetTruck() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VR.Web.UI.Language.Resource_GetTruck", typeof(Resource_GetTruck).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtBienDK.
        /// </summary>
        public static string BienDK {
            get {
                return ResourceManager.GetString("BienDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button1.
        /// </summary>
        public static string Button1 {
            get {
                return ResourceManager.GetString("Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtCaptcha.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to captchaURL.
        /// </summary>
        public static string captchaURL {
            get {
                return ResourceManager.GetString("captchaURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to errorWhenSubmit.
        /// </summary>
        public static string errorWhenSubmit {
            get {
                return ResourceManager.GetString("errorWhenSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __EVENTVALIDATION.
        /// </summary>
        public static string EVENTVALIDATION {
            get {
                return ResourceManager.GetString("EVENTVALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to truckinfo.
        /// </summary>
        public static string truckinfo {
            get {
                return ResourceManager.GetString("truckinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __VIEWSTATE.
        /// </summary>
        public static string VIEWSTATE {
            get {
                return ResourceManager.GetString("VIEWSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __VIEWSTATEGENERATOR.
        /// </summary>
        public static string VIEWSTATEGENERATOR {
            get {
                return ResourceManager.GetString("VIEWSTATEGENERATOR", resourceCulture);
            }
        }
    }
}
