//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VR.Web.UI.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VR.Web.UI.Language.Resource_Config", typeof(Resource_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thất bại.
        /// </summary>
        public static string Alert_error {
            get {
                return ResourceManager.GetString("Alert_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thành công.
        /// </summary>
        public static string Alert_success {
            get {
                return ResourceManager.GetString("Alert_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập ID số trục.
        /// </summary>
        public static string AxleNo_error {
            get {
                return ResourceManager.GetString("AxleNo_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID số trục....
        /// </summary>
        public static string AxleNo_pla {
            get {
                return ResourceManager.GetString("AxleNo_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string btnclose {
            get {
                return ResourceManager.GetString("btnclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string btnsave {
            get {
                return ResourceManager.GetString("btnsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập ID ngày kiểm định.
        /// </summary>
        public static string DateCheck_error {
            get {
                return ResourceManager.GetString("DateCheck_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID ngày kiểm định....
        /// </summary>
        public static string DateCheck_pla {
            get {
                return ResourceManager.GetString("DateCheck_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập ID hạn hiệu lực GCN.
        /// </summary>
        public static string GCNDate_error {
            get {
                return ResourceManager.GetString("GCNDate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID hạn hiệu lực GCN....
        /// </summary>
        public static string GCNDate_pla {
            get {
                return ResourceManager.GetString("GCNDate_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  nhập ID số tem GCN.
        /// </summary>
        public static string GCNStamp_error {
            get {
                return ResourceManager.GetString("GCNStamp_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID số tem GCN....
        /// </summary>
        public static string GCNStamp_pla {
            get {
                return ResourceManager.GetString("GCNStamp_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập ID khối lượng toàn bộ cho phép TGGT.
        /// </summary>
        public static string GrossWeight_error {
            get {
                return ResourceManager.GetString("GrossWeight_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID hối lượng toàn bộ cho phép TGGT....
        /// </summary>
        public static string GrossWeight_pla {
            get {
                return ResourceManager.GetString("GrossWeight_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string lbl_welcome {
            get {
                return ResourceManager.GetString("lbl_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trục.
        /// </summary>
        public static string lblAxleNo {
            get {
                return ResourceManager.GetString("lblAxleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kiểm định.
        /// </summary>
        public static string lblDateCheck {
            get {
                return ResourceManager.GetString("lblDateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn hiệu lực GCN.
        /// </summary>
        public static string lblGCNDate {
            get {
                return ResourceManager.GetString("lblGCNDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tem GCN.
        /// </summary>
        public static string lblGCNStamp {
            get {
                return ResourceManager.GetString("lblGCNStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khối lượng toàn bộ cho phép tham gia giao thông.
        /// </summary>
        public static string lblGrossWeight {
            get {
                return ResourceManager.GetString("lblGrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số người cho phép chở (ngồi).
        /// </summary>
        public static string lblMaxSeat {
            get {
                return ResourceManager.GetString("lblMaxSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khối Lượng Bản Thân.
        /// </summary>
        public static string lblNetWeight {
            get {
                return ResourceManager.GetString("lblNetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khối lượng kéo theo cho phép.
        /// </summary>
        public static string lblTowedWeight {
            get {
                return ResourceManager.GetString("lblTowedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại phương tiện.
        /// </summary>
        public static string lblTruckType {
            get {
                return ResourceManager.GetString("lblTruckType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ Website.
        /// </summary>
        public static string lblWebsiteAddress {
            get {
                return ResourceManager.GetString("lblWebsiteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khối lượng hàng hóa chuyên chở cho phép TGGT.
        /// </summary>
        public static string lblWeightLimit {
            get {
                return ResourceManager.GetString("lblWeightLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập ID số người cho phép chở.
        /// </summary>
        public static string MaxSeat_error {
            get {
                return ResourceManager.GetString("MaxSeat_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID số người cho phép chở ngồi....
        /// </summary>
        public static string MaxSeat_pla {
            get {
                return ResourceManager.GetString("MaxSeat_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập ID khối lượng bản thân.
        /// </summary>
        public static string NetWeight_error {
            get {
                return ResourceManager.GetString("NetWeight_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID khối lượng bản thân....
        /// </summary>
        public static string NetWeight_pla {
            get {
                return ResourceManager.GetString("NetWeight_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu.
        /// </summary>
        public static string PWD_error {
            get {
                return ResourceManager.GetString("PWD_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình tham số lấy tải trọng.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập ID khối lượng kéo theo cho phép.
        /// </summary>
        public static string TowedWeight_error {
            get {
                return ResourceManager.GetString("TowedWeight_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID khối lượng kéo theo cho phép....
        /// </summary>
        public static string TowedWeight_pla {
            get {
                return ResourceManager.GetString("TowedWeight_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập ID loại phương tiện.
        /// </summary>
        public static string TruckType_error {
            get {
                return ResourceManager.GetString("TruckType_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID loại phương tiện....
        /// </summary>
        public static string TruckType_pla {
            get {
                return ResourceManager.GetString("TruckType_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error :.
        /// </summary>
        public static string txt_confi_error {
            get {
                return ResourceManager.GetString("txt_confi_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string txt_confi_succes {
            get {
                return ResourceManager.GetString("txt_confi_succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng!.
        /// </summary>
        public static string User_error {
            get {
                return ResourceManager.GetString("User_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên tài khoản.
        /// </summary>
        public static string USER_NAME_error {
            get {
                return ResourceManager.GetString("USER_NAME_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID địa chỉ website lấy thông tin đăng kiểm.
        /// </summary>
        public static string WebsiteAddress {
            get {
                return ResourceManager.GetString("WebsiteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập website lấy thông tin đăng kiểm.
        /// </summary>
        public static string WebsiteAddress_error {
            get {
                return ResourceManager.GetString("WebsiteAddress_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ website lấy cấu hình tải trọng.
        /// </summary>
        public static string WebsiteAddress_pla {
            get {
                return ResourceManager.GetString("WebsiteAddress_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập ID khối lượng hàng hóa cho phép TGGT.
        /// </summary>
        public static string WeightLimit_error {
            get {
                return ResourceManager.GetString("WeightLimit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID khối lượng hàng hóa cho phép TGGT....
        /// </summary>
        public static string WeightLimit_pla {
            get {
                return ResourceManager.GetString("WeightLimit_pla", resourceCulture);
            }
        }
    }
}
