//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VR.Web.UI.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_LoginHome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_LoginHome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VR.Web.UI.Language.Resource_LoginHome", typeof(Resource_LoginHome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Xuất.
        /// </summary>
        public static string btn_DangXuat {
            get {
                return ResourceManager.GetString("btn_DangXuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập.
        /// </summary>
        public static string btn_value {
            get {
                return ResourceManager.GetString("btn_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file excel lấy thông tin đăng kiểm.
        /// </summary>
        public static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem log file excel.
        /// </summary>
        public static string ButtonLog {
            get {
                return ResourceManager.GetString("ButtonLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRTruck Registation.
        /// </summary>
        public static string lbl_Home {
            get {
                return ResourceManager.GetString("lbl_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong user name or password.
        /// </summary>
        public static string Login_fail {
            get {
                return ResourceManager.GetString("Login_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success.
        /// </summary>
        public static string Login_success {
            get {
                return ResourceManager.GetString("Login_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập.
        /// </summary>
        public static string Login_title {
            get {
                return ResourceManager.GetString("Login_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập mật khẩu....
        /// </summary>
        public static string PWD_pla {
            get {
                return ResourceManager.GetString("PWD_pla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string Session_user {
            get {
                return ResourceManager.GetString("Session_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn chức năng hệ thống.
        /// </summary>
        public static string Title_home {
            get {
                return ResourceManager.GetString("Title_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng!!.
        /// </summary>
        public static string User_error {
            get {
                return ResourceManager.GetString("User_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhập tài khoản....
        /// </summary>
        public static string USER_NAME_pla {
            get {
                return ResourceManager.GetString("USER_NAME_pla", resourceCulture);
            }
        }
    }
}
