//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VR.Web.UI.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_FileExcelUpload {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_FileExcelUpload() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VR.Web.UI.Language.Resource_FileExcelUpload", typeof(Resource_FileExcelUpload).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download File Excel Sample.
        /// </summary>
        public static string DownloadSample {
            get {
                return ResourceManager.GetString("DownloadSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐÃ CÓ LỖI XẢY RA XIN QUAY LẠI TRANG CHỦ.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File&apos;s content is blank.  Please fill in before importing again..
        /// </summary>
        public static string ErrorContentBlank {
            get {
                return ResourceManager.GetString("ErrorContentBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File&apos;s column number is wrong.
        /// </summary>
        public static string ErrorContentSizeWrong {
            get {
                return ResourceManager.GetString("ErrorContentSizeWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has already existed. Please choose another file..
        /// </summary>
        public static string ErrorExisted {
            get {
                return ResourceManager.GetString("ErrorExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose enough information required for uploading.
        /// </summary>
        public static string ErrorNotEnoughParams {
            get {
                return ResourceManager.GetString("ErrorNotEnoughParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors while importing file. Please check your file again..
        /// </summary>
        public static string ErrorNotFinished {
            get {
                return ResourceManager.GetString("ErrorNotFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something&apos;s wrong on the server..
        /// </summary>
        public static string ErrorServer {
            get {
                return ResourceManager.GetString("ErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose file excel..
        /// </summary>
        public static string ErrorWrongExtension {
            get {
                return ResourceManager.GetString("ErrorWrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Excel File.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadButton {
            get {
                return ResourceManager.GetString("UploadButton", resourceCulture);
            }
        }
    }
}
